### ISSUE TITLE
Rumble: Playback in background error

### ISSUE THREAD

**Issue by fedelibre** [bravepipeproject/BravePipeExtractor#17] opened 2021-11-03 22:49 UTC
When I try to play back the audio in background in a Rumble video I get an error. This does not happen when using Youtube.
The error is something like (translating from my mother language):

> A fatal media player error occurred

Audio in background is one of the main reason why I use NewPipe...

My phone has Lineage OS 15.1-2020224.
Let me know if you need more information.

Thanks

**Comment by evermind-zz** [comment] 2021-11-15 07:21
Could you provide a link for a video where this error occured? I will try to reproduce it

**Comment by fedelibre** [comment] 2021-11-15 14:12
It happens with any video.

I noticed another problem: when I try to download the *audio* of a clip, the video is downloaded instead. It seems it cannot handle the audio at all.

If I go in the Download section of BrandNewPipe, I see the file with the headphones icon (suggesting it's an audio file), but when I click on it the video is loaded.
If I click on More info, I get the following error:

```
{"user_action":"requested stream","request":"https://rumble.com/vp8s2y","content_language":"it-IT","content_country":"IT","app_language":"it_IT","service":"Rumble","package":"com.github.bravenewpipe","version":"0.21.13-1.0.3","os":"Linux Android 8.1.0 - 27","time":"2021-11-15 15:09","exceptions":["java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at org.schabi.newpipe.extractor.services.rumble.extractors.RumbleStreamExtractor.getViewCount(RumbleStreamExtractor.java:131)
        at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:261)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
        at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
        at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
        at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
        at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
        at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
"],"user_comment":""}"
```

**Comment by evermind-zz** [comment] 2021-11-15 14:32
The problem is due to that Rumble has no real audio files. I just faked the video ones into appearing to be audio files for background playback. I am pretty sure that I can't fix that here in NewPipeExtractor that BraveNewPipe will extract the audio from the video.

**Comment by evermind-zz** [comment] 2022-05-03 20:00
removed fake audio functionality with d773536c7f5aa4c8ee852532e42108bd0abb0af1

**Comment by bloatmode** [comment] 2022-12-15 19:17
@evermind-zz Wouldn't it be possible to stream both video and audio but play just the audio while in background mode?

**Comment by evermind-zz** [comment] 2022-12-15 20:00
@bloatmode actually it is working this way now

**Comment by bloatmode** [comment] 2022-12-15 23:09
@evermind-zz Not really, if I click "Background" when inside a playlist I get this exception and nothing is played in the background:

## Exception
* __User Action:__ play stream
* __Request:__ Loading failed for [China Covid Protests - Who Are The REAL Dictators?]: https://rumble.com/v1zg60n-china-covid-protests-who-are-the-real-dictators.html
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ Rumble
* __Version:__ 0.24.1-2.0.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.player.mediasource.FailedMediaSource$MediaSourceResolutionException: Unable to resolve source from stream info. URL: https://rumble.com/v1zg60n-china-covid-protests-who-are-the-real-dictators.html, audio count: 0, video count: 0, 6
	at org.schabi.newpipe.player.playback.MediaSourceManager.lambda$getLoadedMediaSource$3(MediaSourceManager.java:432)
	at org.schabi.newpipe.player.playback.MediaSourceManager.$r8$lambda$GiL2pCn9PgSZNVk872SsYVyH27I(Unknown Source:0)
	at org.schabi.newpipe.player.playback.MediaSourceManager$$ExternalSyntheticLambda4.apply(Unknown Source:6)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:136)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

**Comment by evermind-zz** [comment] 2022-12-16 00:02
I'll look into it. What I was referring to is: playing one video in the foreground and then turn the display off. This should work.

**Comment by evermind-zz** [comment] 2022-12-16 23:12
@bloatmode  So I added the ability to BraveNewPipe to also play the audio of videos in the background. It will use the resolution that is defined for the video player. Can you please test it?
[app-brave-debug.zip](https://github.com/bravenewpipe/NewPipeExtractor/files/10249925/app-brave-debug.zip)

**Comment by bloatmode** [comment] 2022-12-17 02:05
@evermind-zz It works, thanks!

**Comment by evermind-zz** [comment] 2023-01-10 08:02
Fox merged 
with https://github.com/TeamNewPipe/NewPipe/pull/9562

**Closed as completed by evermind-zz** 2023-01-10 08:02 UTC
