### ISSUE TITLE
Network error on Rumble: Too many follow-up requests: 21

### ISSUE THREAD

**Issue by inspiredearth** [bravepipeproject/BravePipeExtractor#73] opened 2023-02-04 19:19 UTC
App is unable to c9nnect to internet.

No issue with any other apps connecting to Internet. Including Newpipe. It appears to just be an issue with bravenewpipe. Surely other people must be having the same problem? So I'm not sure why it hasn't been reported. 

Below is the report generated by the app.

```
## Exception
* __User Action:__ requested kiosk
* __Request:__ Start loading: https://rumble.com/category/news
* __Content Country:__ NZ
* __Content Language:__ en-NZ
* __App Language:__ en_NZ
* __Service:__ Rumble
* __Version:__ 0.24.1-2.0.1
* __OS:__ Linux samsung/a53xnsxx/a53x:13/TP1A.220624.014/A536EXXU4BVL3:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>


java.net.ProtocolException: Too many follow-up requests: 21
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:163)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:75)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:30)
	at org.schabi.newpipe.extractor.services.rumble.extractors.RumbleTrendingExtractor.onFetchPage(RumbleTrendingExtractor.java:39)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:53)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:192)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$NbG7JFGg0N9HK-3exJNRB9r_hYY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

</details>
<hr>
```

**Comment by feelingwalnut** [comment] 2023-02-04 21:46
appears to be back up.
it was affecting me earlier today, simply gave it time.

**Comment by evermind-zz** [comment] 2023-02-04 22:09
I've seen that behavior first after download failed. It turned out that they do no longer allow the use of HEAD over the GET http method. But maybe it is also related to not using cookies in the request headers.

I've a fix for the download thingy but have to do some more testing.

Maybe it is just a glitch and they fix their mess or it is by design. I'll look into it if I find some time.

**Comment by feelingwalnut** [comment] 2023-02-04 22:12
> I've seen that behavior first after download failed. It turned out that they do no longer allow the use of HEAD over the GET http method. But maybe it is also related to not using cookies in the request headers.
> 
> I've a fix for the download thingy but have to do some more testing.
> 
> Maybe it is just a glitch and they fix their mess or it is by design. I'll look into it if I find some time.

bingo, i forgot i'd tried rumble download the other day and hadn't used it since.
the downloads failed.

**Comment by evermind-zz** [comment] 2023-02-06 00:26
Fixed in https://github.com/bravenewpipe/NewPipe/releases/tag/v0.24.1-2.0.2

**Closed as completed by evermind-zz** 2023-02-06 00:26 UTC
